//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibraryApp.Models
{
    using System;

    public partial class BookCopy
    {
        public int Id { get; set; }
        public string inventory_number { get; set; }
        public bool is_available { get; set; }
        public System.DateTime take_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
        public Nullable<int> book_id { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
