//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineLibraryApp.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class OnlineLibraryDbEntities1 : DbContext
    {
        public OnlineLibraryDbEntities1()
            : base("name=OnlineLibraryDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Book> Book { get; set; }
        public virtual DbSet<BookCopy> BookCopy { get; set; }
        public virtual DbSet<Books_Authors> Books_Authors { get; set; }
        public virtual DbSet<spr_Sex> spr_Sex { get; set; }
        public virtual DbSet<Subscription> Subscription { get; set; }
        public virtual DbSet<Subscriptions_Books> Subscriptions_Books { get; set; }
    }
}
