//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace OnlineLibraryApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subscription()
        {
            this.Subscriptions_Books = new HashSet<Subscriptions_Books>();
        }
    
        public int Id { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 2)]
        public string last_name { get; set; }
        [Required]
        [StringLength(50, MinimumLength = 1)]
        public string first_name { get; set; }
        [Required]
        [StringLength(9, MinimumLength = 1)]
        public string subscription_number { get; set; }
        public Nullable<int> sex_id { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime birth_date { get; set; }
        public string phone { get; set; }
    
        public virtual spr_Sex spr_Sex { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscriptions_Books> Subscriptions_Books { get; set; }
    }
}
